name: Deploy Backend to Railway

on:
  push:
    branches:
      - master  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Step 5: Authenticate Railway
      - name: Authenticate Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway login --token $RAILWAY_API_TOKEN

      # Step 6: Deploy to Railway
      - name: Deploy to Railway
        run: railway up
